---
name: Manual maven steps for ci
on:
    pull_request:
      branches: 
        - main
    workflow_dispatch:

permissions:
  contents: read
  checks: write
  pull-requests: write
  actions: read
  security-events: write

jobs:
    manual:
        runs-on: ubuntu-24.04
        strategy:
          fail-fast: false
          matrix:
            java: [21]

        steps:
          - uses: actions/checkout@v5
          - uses: actions/setup-java@v5
            with:
                distribution: 'temurin'
                java-version: ${{ matrix.java }}
                cache: maven
          - name: Initialize CodeQL
            uses: github/codeql-action/init@v3
            with:
              languages: java
          - name: build package
            run: mvn ${{ vars.GOAL  }}
          - name: Perform CodeQL Analysis
            uses: github/codeql-action/analyze@v3
          - name: publish test results
            uses: EnricoMi/publish-unit-test-result-action@v2
            with:
              files: |
                **/target/surefire-reports/*.xml
          - name: Uploading packaged jar files
            uses: actions/upload-artifact@v4
            with:
              name: spring-petclinic-${{ matrix.java }}.jar
              path: '**/target/*.jar'
          
          
            

